// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pasteimg.Backend.Data;

#nullable disable

namespace Pasteimg.Backend.Migrations
{
    [DbContext(typeof(PasteImgDbContext))]
    [Migration("20230402101053_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Pasteimg.Backend.Models.Admin", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Email");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Email = "admin@admin.com",
                            Password = "dcf87619f0fffee3424fbda793be9adf14cd67f01713c4632d34299b45a5bdb6"
                        });
                });

            modelBuilder.Entity("Pasteimg.Backend.Models.Image", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NSFW")
                        .HasColumnType("bit");

                    b.Property<string>("UploadId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("UploadId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Pasteimg.Backend.Models.Upload", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TimeStamp");

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("Pasteimg.Backend.Models.Image", b =>
                {
                    b.HasOne("Pasteimg.Backend.Models.Upload", "Upload")
                        .WithMany("Images")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("Pasteimg.Backend.Models.Upload", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
