var namespace_pasteimg_1_1_backend_1_1_data_1_1_migrations =
[
    [ "ApplicationDbContextModelSnapshot", "class_pasteimg_1_1_backend_1_1_data_1_1_migrations_1_1_application_db_context_model_snapshot.html", "class_pasteimg_1_1_backend_1_1_data_1_1_migrations_1_1_application_db_context_model_snapshot" ],
    [ "CreateIdentitySchema", "class_pasteimg_1_1_backend_1_1_data_1_1_migrations_1_1_create_identity_schema.html", "class_pasteimg_1_1_backend_1_1_data_1_1_migrations_1_1_create_identity_schema" ]
];